[build]
    command = "npm run build"
    publish = "dist"

[context.production.environment]
    NODE_ENV = "production"

[template.environment]
    META_TITLE = "Testing for COVID-19"
    META_URL = "https://github.com/designtocombatcovid19/testing-locations"
    META_DESC = "Locations, hours, and eligibility for COVID-19 testing in the United States."
    META_LANG = "en"
    META_COLOR = ""
    META_EMAIL = "locations@designtocombatcovid19.com"
    META_TELEPHONE = ""
    # TZ = "the timezone for your site, e.g. America/New_York"

[[redirects]]
    from = "*"
    to = "/404"
    status = 404
